// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgNHQES0tJJfMrzhrmi5M1jwXXqYKIZm0',
    appId: '1:666492570428:web:8604792f794199bd752c39',
    messagingSenderId: '666492570428',
    projectId: 'gruppo-21-progetto',
    authDomain: 'gruppo-21-progetto.firebaseapp.com',
    storageBucket: 'gruppo-21-progetto.appspot.com',
    measurementId: 'G-CXJ5ZSW9NH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXFPcWWGKomjbiFCJv0wZwC30-MaEe-2g',
    appId: '1:666492570428:android:f2add576e71608c8752c39',
    messagingSenderId: '666492570428',
    projectId: 'gruppo-21-progetto',
    storageBucket: 'gruppo-21-progetto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlVNbVDahqxDsBnjJ5cRFHyhpWW-NsdTQ',
    appId: '1:666492570428:ios:4b021454b69b2ac5752c39',
    messagingSenderId: '666492570428',
    projectId: 'gruppo-21-progetto',
    storageBucket: 'gruppo-21-progetto.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlVNbVDahqxDsBnjJ5cRFHyhpWW-NsdTQ',
    appId: '1:666492570428:ios:4b021454b69b2ac5752c39',
    messagingSenderId: '666492570428',
    projectId: 'gruppo-21-progetto',
    storageBucket: 'gruppo-21-progetto.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgNHQES0tJJfMrzhrmi5M1jwXXqYKIZm0',
    appId: '1:666492570428:web:df10a1e2923b022a752c39',
    messagingSenderId: '666492570428',
    projectId: 'gruppo-21-progetto',
    authDomain: 'gruppo-21-progetto.firebaseapp.com',
    storageBucket: 'gruppo-21-progetto.appspot.com',
    measurementId: 'G-29YPT2LLRN',
  );
}
